// import type { Metadata } from "next";
// import { Outfit } from "next/font/google";
// import "./globals.css";
// import Navbar from "./components/layouts/navbar";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// const outfit = Outfit({
//   variable: "--font-outfit",
//   subsets: ["latin"],
//   display: "swap",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${outfit.variable} antialiased`}
//       >
//         <Navbar />
//         <main>
//           {children}
//         </main>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

import Header from "./components/layouts/Header";
import Providers from "./providers"; // 👈 we'll create this
import Footer from "./components/layouts/footer";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "L.A. Apex Technologies - Innovative Tech Solutions",
  description: "Empowering businesses through software development, data intelligence, and automation. Professional tech consulting and digital transformation services.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} antialiased`}>
        <Header />
        <Providers>
          <main>{children}</main>
        </Providers>
        <Footer />
      </body>
    </html>
  );
}

